# Generated by Django 4.0.1 on 2022-02-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(choices=[('Reach Us', 'Reach Us'), ('Feedback', 'Feedback'), ('Raise a Complaint', 'Raise a Complaint')], max_length=200, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('service', models.CharField(max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=200, null=True)),
                ('date_needed', models.DateField(null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('rent_item', models.CharField(max_length=200, null=True)),
                ('its_name', models.CharField(max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
