# Generated by Django 4.0.1 on 2022-02-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jetexapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hire',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='hire',
            name='date_needed',
        ),
        migrations.RemoveField(
            model_name='hire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hire',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hire',
            name='service',
        ),
    ]
