# Generated by Django 4.0.1 on 2022-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetexapp', '0002_remove_hire_address_remove_hire_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='contact_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='date_needed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='service',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
