# Generated by Django 4.0.1 on 2022-02-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetexapp', '0003_hire_address_hire_contact_no_hire_date_needed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
