# Generated by Django 4.0.1 on 2022-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetexapp', '0004_professionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
